### ISSUE TITLE
Saavutettavuus

### ISSUE THREAD

**Issue by elkku26** [kajo2022/kajo22-pestikone-frontend#17]
Pyritään mieluusti tekemään sovellus niin että se olisi mahdollisimman ystävällinen esim. screen readereille. https://wave.webaim.org/ on kiva sivu jolla voi tarkistaa, minkälaisia juttuja voisi lisätä/muuttaa että saavutettavuus paranisi.

**Comment by Ode42** [comment]
Valmista!
