### ISSUE TITLE
Responsiivisuus

### ISSUE THREAD

**Issue by elkku26** [kajo2022/kajo22-pestikone-frontend#18]
Pyritään siihen että sovellus toimii mahdollisimman mukavasti ainakin erikokoisilla näytöillä ja mahdollisesti myös puhelimilla. Tällä hetkellä se skaalaa omassa tapauksessa aika heikosti ainakin puhelimella ja läppärin näytöllä.

**Comment by RVeridium** [comment]
pitää vähän ehdollistaa sitä Style.jsx, se toimii kai aika samalla tavalla kun bootstrap. Joka tapauksessa tästä voi tulla aika härö jos se optimoidaan myös mobiilille.

**Comment by Ode42** [comment]
Valmista!
