### ISSUE TITLE
Chat boxi näyttö

### ISSUE THREAD

**Issue by Ode42** [kajo2022/kajo22-pestikone-frontend#3]
Näkymä jossa on chatbot joka esittää kysymykset. Botin kysymykset vasemmalla ja oma vastausruutu oikealla. Ruutua voi scrollata ja katsoa omia vastauksia ja muokata.

**Comment by RVeridium** [comment]
Onko näkynyt yhtään toimivia plugeja tähän? Koska mun testikeissit oli sieltä ja syvältä. Mutta animaation saa ehkä jollain muulla kirjastolla, jos ei ole sisäänrakennettu.

**Comment by Ode42** [comment]
@elkku26 pushaa muutokset tänne nettiin, ne on varmaan vielä siellä sulla lokaalisti. Löyty joku kirjasto ainakin, pitää kattoa kuinka hyvä se on. Transitiota ei ollut sisäänrakennettuna mutta sen saa tehtyä itse tai jollain kirjastolla luultavasti.

**Comment by RVeridium** [comment]
tämä on nyt varmaan tehty
